package com.eventosdahora.payment.ms.dominio;

public enum PedidoEvent {
    RESERVAR_TICKET, RESERVA_TICKET_APROVADO, RESERVA_TICKET_NEGADO,
    PAGAR_TICKET, PAGAR_TICKET_APROVADO, PAGAR_TICKET_NEGADO,
    CONSOLIDAR_COMPRA, CONSOLIDACAO_COMPRA_APROVADO,
    RESTAURAR_TICKET, TICKET_RESTAURADO_APROVADO, TICKET_RESTAURADO_NEGADO
}
